### ISSUE TITLE
When exactly will the pre-trained models be released?

### ISSUE THREAD

**Issue by nosaydomore** [XingangPan/Switchable-Whitening#2]
Thanks for your excellent work. Could you tell me when exactly the pre-trained models will be released?

**Comment by XingangPan** [comment]
@nosaydomore The pretrained ResNet50 with SW is available at https://drive.google.com/open?id=1c1Z0ubLkdVmlj2Fb-FAzKrUg1m5RA3Jl

**Comment by nosaydomore** [comment]
@XingangPan thank you

**Comment by SystemErrorWang** [comment]
> https://drive.google.com/open?id=1c1Z0ubLkdVmlj2Fb-FAzKrUg1m5RA3Jl

this link seems to be invalid anymore

**Comment by XingangPan** [comment]
@SystemErrorWang Please refer to this new link: https://drive.google.com/drive/folders/1dUK0hJ_FYXP45LDJnAW_vjNGRoAP4Byb
