### ISSUE TITLE
where to use SW?

### ISSUE THREAD

**Issue by Jinjicheng** [XingangPan/Switchable-Whitening#3]
In model, i only see resnet50,and do not see SW. How do you use SW?

**Comment by XingangPan** [comment]
@Jinjicheng For the initialization function of ResNet, there are two parameters 'sw_cfg' and 'stage_with_sw', which defines configurations of SW and the stages to use SW.  Please also refer to 'build_norm_layer' function at models/utils/norm.py

**Comment by Jinjicheng** [comment]
Thank you! I will see carefully.
