### ISSUE TITLE
loading state dict failed

### ISSUE THREAD

**Issue by chenbinghui1** [XingangPan/Switchable-Whitening#4]
Hi, 
when I loading the parameters with your pretrained model, a strange problem happens. It looks like below:

While copying the parameter named "sw1.running_cov", whose dimensions in the model are  While copying the parameter named "sw1.running_cov", whose dimensions in the model are torch.Size([4, 16, 16]) and whose dimensions in the checkpoint are torch.Size([4, 16, 16]).
        While copying the parameter named "layer1.1.sw2.running_cov", whose dimensions in the model are torch.Size([4, 16, 16]) and whose dimensions in the checkpoint are torch.Size([4, 16, 16]).
        While copying the parameter named "layer2.1.sw2.running_cov", whose dimensions in the model are torch.Size([8, 16, 16]) and whose dimensions in the checkpoint are torch.Size([8, 16, 16]).
        While copying the parameter named "layer2.3.sw2.running_cov", whose dimensions in the model are torch.Size([8, 16, 16]) and whose dimensions in the checkpoint are torch.Size([8, 16, 16]).
        While copying the parameter named "layer3.1.sw2.running_cov", whose dimensions in the model are torch.Size([16, 16, 16]) and whose dimensions in the checkpoint are torch.Size([16, 16, 16]).
        While copying the parameter named "layer3.3.sw2.running_cov", whose dimensions in the model are torch.Size([16, 16, 16]) and whose dimensions in the checkpoint are torch.Size([16, 16, 16]).
        While copying the parameter named "layer3.5.sw2.running_cov", whose dimensions in the model are torch.Size([16, 16, 16]) and whose dimensions in the checkpoint are torch.Size([16, 16, 16]).
        While copying the parameter named "layer3.7.sw2.running_cov", whose dimensions in the model are torch.Size([16, 16, 16]) and whose dimensions in the checkpoint are torch.Size([16, 16, 16]).
        While copying the parameter named "layer3.9.sw2.running_cov", whose dimensions in the model are torch.Size([16, 16, 16]) and whose dimensions in the checkpoint are torch.Size([16, 16, 16]).
        While copying the parameter named "layer3.11.sw2.running_cov", whose dimensions in the model are torch.Size([16, 16, 16]) and whose dimensions in the checkpoint are torch.Size([16, 16, 16]).
        While copying the parameter named "layer3.13.sw2.running_cov", whose dimensions in the model are torch.Size([16, 16, 16]) and whose dimensions in the checkpoint are torch.Size([16, 16, 16]).
        While copying the parameter named "layer3.15.sw2.running_cov", whose dimensions in the model are torch.Size([16, 16, 16]) and whose dimensions in the checkpoint are torch.Size([16, 16, 16]).
        While copying the parameter named "layer3.17.sw2.running_cov", whose dimensions in the model are torch.Size([16, 16, 16]) and whose dimensions in the checkpoint are torch.Size([16, 16, 16]).
        While copying the parameter named "layer3.19.sw2.running_cov", whose dimensions in the model are torch.Size([16, 16, 16]) and whose dimensions in the checkpoint are torch.Size([16, 16, 16]).
        While copying the parameter named "layer3.21.sw2.running_cov", whose dimensions in the model are torch.Size([16, 16, 16]) and whose dimensions in the checkpoint are torch.Size([16, 16, 16]).

The input_param and param indeed have the same shape, but why they cannot be loaded.? Have you met this problem?

**Comment by chenbinghui1** [comment]
This seems to be caused by the definition of 'running_cov'. in your code, it is defined by torch.eye(xx).expand(), where 'expand' will cause the copy_() problem when using load_state_dict(). I change 'expand()' to  'repeat()', and the parameter loading problem is addressed. So I think the original code should be updated for correct parameter loading if what I said is right!

**Comment by XingangPan** [comment]
@chenbinghui1 Thanks, I'll check and fix it.
