### ISSUE TITLE
RuntimeError: mul: unsupported operation: more than one element of the written-to tensor refers to a single memory location

### ISSUE THREAD

**Issue by yuzhijun2** [XingangPan/Switchable-Whitening#5]
Ifind an error in code switchwhiten.py
self.running_cov.mul_(self.momentum) 

error info:
RuntimeError: mul: unsupported operation: more than one element of the written-to tensor refers to a single memory location

I modify：
self.running_cov = self.running_cov.mul(self.momentum)

**Comment by XingangPan** [comment]
@yuzhijun2 Which pytorch version do you use? I do not observe such error in pytorch1.1.
self.running_cov should be updated with inplace operation, your modification may lead to inaccurate results in eval mode.

**Comment by Adorablepet** [comment]
@XingangPan Thanks.I also encountered a similar error, when I loaded the pre-trained model, I got this error “while copying the parameter named "sw1.conv", whose dimensions in the model are torch.size([4,16,16]) and whose dimensions in the checkpoint are torch.size([4,16,16])”.As long as everything related to running_conv reported the same error.

**Comment by Adorablepet** [comment]
@XingangPan pytorch 1.3

**Comment by XingangPan** [comment]
@yuzhijun2 @Adorablepet I have changed 'expand(self.num_groups, num_pergroup, num_pergroup))' to 'unsqueeze(0).repeat(self.num_groups, 1, 1))' for the initialization of running_cov. Please take a look if this solve the issue.

**Comment by yuzhijun2** [comment]
thanks!!!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xingang Pan"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月18日(星期三) 下午3:38
收件人:&nbsp;"XingangPan/Switchable-Whitening"<Switchable-Whitening@noreply.github.com&gt;;
抄送:&nbsp;"余智君"<872528229@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [XingangPan/Switchable-Whitening] RuntimeError: mul: unsupported operation: more than one element of the written-to tensor refers to a single memory location (#5)




@yuzhijun2 @Adorablepet I have changed 'expand(self.num_groups, num_pergroup, num_pergroup))' to 'unsqueeze(0).repeat(self.num_groups, 1, 1))' for the initialization of running_cov. Please take a look if this solve the issue.

**Comment by Adorablepet** [comment]
@XingangPan OK,. The problem has been solved.Thanks.
